import type { Metadata } from "next";
import {DM_Sans} from "next/font/google";
import "./globals.css";

const AppFont = DM_Sans({subsets:['latin']})

export const metadata: Metadata = {
  title: "AI Video Course Generator App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={AppFont.className}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
